---
driver:
  name: docker

provisioner:
  name: chef_zero
  data_bags_path: 'test/fixtures/data_bags'
  clients_path: 'test/fixtures/clients'

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: centos-6.6
  - name: centos-7
suites:
  - name: default
    run_list:
      - recipe[vault_test::default]
    attributes:
